-- Vaultra evidence persistence v1
-- Run in Supabase SQL editor before enabling SUPABASE_* in Vercel.

create extension if not exists pgcrypto;

create table if not exists public.scan_runs (
  id uuid primary key default gen_random_uuid(),
  chain text not null check (chain in ('sol','bsc','base','eth','robinhood','arc','stable')),
  provider text not null default 'gmgn',
  generated_at timestamptz not null,
  candidate_count integer not null default 0 check (candidate_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_snapshots (
  id bigint generated by default as identity primary key,
  scan_run_id uuid not null references public.scan_runs(id) on delete cascade,
  chain text not null check (chain in ('sol','bsc','base','eth','robinhood','arc','stable')),
  wallet_address text not null,
  token_address text,
  token_symbol text,
  observed_amount_usd numeric,
  observed_at timestamptz,
  surface_state text not null,
  score jsonb,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wallet_snapshots_lookup_idx on public.wallet_snapshots(chain, wallet_address, created_at desc);
create index if not exists wallet_snapshots_state_idx on public.wallet_snapshots(chain, surface_state, created_at desc);

alter table public.scan_runs enable row level security;
alter table public.wallet_snapshots enable row level security;

-- Server-side service-role writes only. No public client access in v1.
revoke all on public.scan_runs from anon, authenticated;
revoke all on public.wallet_snapshots from anon, authenticated;
